# Generated by Django 5.0.6 on 2024-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
