# Generated by Django 5.0.6 on 2024-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='user',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
