# Generated by Django 5.0.6 on 2024-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_impressora', models.CharField(default='192.168.122.64', max_length=15)),
                ('codigo_zpl', models.TextField(default='\n    ^XA\n    ^CF0,20\n    ^FO40,20^BQN,2,3^FR^FDMA,{{ticket_number}}^FS\n    {{etiquetas}}\n    ^XZ\n    ')),
            ],
        ),
    ]
