# Generated by Django 5.0.6 on 2024-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTopicLabelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_topic_id', models.IntegerField(unique=True)),
                ('label_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Help Topic Label Mapping',
                'verbose_name_plural': 'Help Topic Label Mappings',
            },
        ),
        migrations.DeleteModel(
            name='Configuracao',
        ),
    ]
